// Re-export shared types for convenience
export type {
  WorkerStatus,
  WorkerInfo,
  WorkerRegistration,
  ContainerStatus,
  ContainerInfo,
  ContainerCreateRequest,
  ContainerLabels,
  TerminalSession,
  TerminalOpenRequest,
  TerminalResizeRequest,
  TicketProvider,
  TicketComment,
  NormalizedTicket,
  WorkerRegisterMessage,
  WorkerHeartbeatMessage,
  ContainerCreatedMessage,
  ContainerStoppedMessage,
  ContainerListResponseMessage,
  TerminalOpenedMessage,
  TerminalOutputMessage,
  TerminalClosedMessage,
  WorkerMessage,
  WorkerAcceptedMessage,
  ContainerCreateMessage,
  ContainerStopMessage,
  ContainerListMessage,
  TerminalOpenMessage,
  TerminalInputMessage,
  TerminalResizeMessage,
  TerminalCloseMessage,
  OrchestratorMessage,
  TerminalBrowserResizeMessage,
  BrowserTerminalMessage,
} from '@code-farm/shared';
